name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
